### ISSUE TITLE
Calling sportdb new en causes error...

### ISSUE THREAD

**Issue by aaraia** [sportdb/sport.db#10]
On Windows 10 + ruby 2.5, i get the below error when calling "sportdb new en"

*** error: undefined method `get_input_stream' for nil:NilClass

Can you help?

Heres the preceeding output...

[info] parsing data in zip 'setups/all' (eng-england-master/setups/all.txt)...
[info] parsing data in zip (league) 'eng-england!/leagues' (eng-england-master/leagues.txt)...
DEPRECATION WARNING: update_attributes! is deprecated and will be removed from Rails 6.1 (please, use update! instead) (called from load at C:/Ruby25-x64/bin/sportdb:23)
DEPRECATION WARNING: update_attributes! is deprecated and will be removed from Rails 6.1 (please, use update! instead) (called from load at C:/Ruby25-x64/bin/sportdb:23)
DEPRECATION WARNING: update_attributes! is deprecated and will be removed from Rails 6.1 (please, use update! instead) (called from load at C:/Ruby25-x64/bin/sportdb:23)
DEPRECATION WARNING: update_attributes! is deprecated and will be removed from Rails 6.1 (please, use update! instead) (called from load at C:/Ruby25-x64/bin/sportdb:23)
[info] parsing data in zip (team) 'eng-england!/clubs/1-premierleague' (eng-england-master/clubs/1-premierleague.txt)...

*** error: undefined method `get_input_stream' for nil:NilClass

**Comment by geraldb** [comment]
Hello, as posted on the other ticket / issue you opened:

Welcome to football.db.  Sorry I'm (re)organizing, that is, trying to make the setup simpler / easier  I will need some more weeks to get it all up-to-date.  Thanks for the patience will things break. For questions and support, please use the forum <https://github.com/openfootball/eng-england#questions-comments>.

PS:  If you try to fix it, the club setup gets reworked. In the meantime you can use the football.csv datasets, see <https://github.com/footballcsv> that are already up-to-date to the "new" system.

**Comment by romeopt** [comment]
Hi,I am new to Ruby,when launching the commande sportdb serve: it produces following erros:
Connecting to db using settings: 
{:adapter=>"sqlite3", :database=>"./sport.db"}
before add middleware ConnectionManagement

*** error: uninitialized constant SportDb::Service::Server

could you find a solution for this?

**Comment by geraldb** [comment]
Thanks for reporting. I pushed out a new gem update to reactive the old serve command  (a new version is coming in the next days). 
Try $ gem install sportdb      and restart / retry. Cheers. Prost.

**Comment by geraldb** [comment]
@romeopt   FYI: I uploaded a new sportdb version, that is, v2.3.0 that now includes the new service (HTTP JSON API) machinery.  Update / restart / retry.  For more docu, see <https://github.com/sportdb/sport.db.service>. Cheers. Prost.

**Comment by romeopt** [comment]
wow! that's great, thank you so much

**Comment by romeopt** [comment]
Hello;
I have encountered a problem when access these endpoints /events, /event/france.2019/20/teams ... from the localhost:9292 or localhost:4567?how could it be.had I miss any steps?

**Comment by geraldb** [comment]
Hard to tell, please post the error the (support) forum <https://groups.google.com/group/opensport>. 
 and include what datasets you have read in (for testing).  This issue is long closed :-).   Try to change the season in the endpoint /event/france.2019/20/teams to /event/france.2019_20/teams

**Comment by romeopt** [comment]
ok, thank for your reply
