### ISSUE TITLE
Search functionality?

### ISSUE THREAD

**Issue by rubyFeedback** [sportdb/sport.db#11]
Hello,

Would you think it would be possible to add a search functionality?

I am often listening to local radio stations, usually music, sometimes also sport commentary, and sometimes I'd like to search for radio stations or simply some ongoing results.

I don't know if there is an easy way for sportdb to discover this, or even independent of sportdb, but perhaps there may be some "discover" / "search" functionality that might allow us to search for something "interesting"; on the commandline?

Or in other ways: a functionality within sportdb itself that would allow us to explore some sports-related stuff, which could then be combined with other, already existing functionality within sportdb. Not sure if this makes sense or is easy to add but if anyone feels bored ... well. :)

Feel free to close this issue if it seems out of scope for the project or too much work.

**Comment by geraldb** [comment]
Thanks for your thoughts and comments. You are invited to join / post to the official discussion forum / mailing list. See <https://github.com/sportdb/sport.db#questions-comments>. The issues here are just for bugs (because there's nobody here). Thanks. Cheers.
