### ISSUE TITLE
I can only import one football worldcup but I want the full history

### ISSUE THREAD

**Issue by zoomore** [sportdb/sport.db#7]
Hi, 
thank you for this amazing work.

I am trying to import the full history of all worldcup by running:
`sportdb new worldcup` 
But I only get a sqlite database with worldcup2014

If I run `sportdb new worldcup2018`  I only get the worldcup 2018 database
I tried unziping: `world-cup-master`
and found that in the `setups` folder and `all.txt` is having this content:
```
###########
# All

# Note: just latest world cup - e.g. Brazil 2014 w/ Quali(fiers)
#
# -- use history.txt for all world cups

# -- Brazil 2014 Quali(fiers)
world-cup!/2014--brazil/quali/africa
world-cup!/2014--brazil/quali/asia
world-cup!/2014--brazil/quali/europe
world-cup!/2014--brazil/quali/north_america
world-cup!/2014--brazil/quali/pacific
world-cup!/2014--brazil/quali/playoffs
world-cup!/2014--brazil/quali/south_america

# -- Brazil 2014
world-cup!/2014--brazil/cup

```
Is this the problem here? How can I solve it?
Thanks

**Comment by geraldb** [comment]
Please send your "I can only import one football worldcup but I want the full history" questions to the forum / mailinglist <http://groups.google.com/group/opensport>. Cheers. Prost.
